In [ ]:
import numpy as np
#random module is sub pacakge in numpy

In [ ]:
a=np.random.rand(1)
print(a)

[0.22975704]


In [ ]:
a=np.random.rand(8,4)#rand range is in b/w 0 and 1
print(a)

[[0.34937923 0.24678692 0.55374846 0.73025869]
 [0.71213702 0.074126   0.30681432 0.77584638]
 [0.35185022 0.83818047 0.10192129 0.97941619]
 [0.79967963 0.57098792 0.69167152 0.02623299]
 [0.52514733 0.6959197  0.16247685 0.48007103]
 [0.49316527 0.77033029 0.68712134 0.59277137]
 [0.04813535 0.40737189 0.60943912 0.45348719]
 [0.34647358 0.05482996 0.65099123 0.65178965]]


In [ ]:
a=10*np.random.rand(8,4)#rand range is in b/w 0 and 1
print(a)

[[9.81869023 1.58667028 9.5662499  4.8377747 ]
 [1.73703926 8.40820249 0.9149554  4.97807964]
 [0.2011202  6.85414148 2.97022404 6.23687522]
 [4.19887605 1.99765427 4.28714812 6.79357003]
 [4.85253715 3.12546848 0.08638084 2.7588413 ]
 [2.45487379 6.42874592 3.45850614 8.40931948]
 [7.72693036 6.49581765 8.32023929 9.70795121]
 [3.28272707 5.17074789 6.95495011 8.13824254]]


In [ ]:
a=np.floor(10*np.random.rand(8,4))#rand range is in b/w 0 and 1
print(a)

[[0. 4. 1. 5.]
 [8. 3. 5. 4.]
 [6. 9. 9. 3.]
 [3. 4. 5. 2.]
 [3. 9. 9. 8.]
 [8. 0. 3. 7.]
 [7. 7. 6. 4.]
 [1. 2. 9. 5.]]


In [ ]:
a=np.arange(1,33).reshape(8,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


splitting an array

In [ ]:
np.vsplit(a,4)#vertical split can be done only when the given num is a multiple of no of rows

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(a,(2,7))#splits after 2nd line and 7th line

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28]]),
 array([[29, 30, 31, 32]])]

In [ ]:
b=np.arange(1,33).reshape(4,8)
print(b)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(b,4)#horizntal split

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(b,(2,3,6))#splits after 2nd,3rd and 6th column

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3],
        [11],
        [19],
        [27]]),
 array([[ 4,  5,  6],
        [12, 13, 14],
        [20, 21, 22],
        [28, 29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

Trignometry and statistics

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
B=np.rad2deg(A)#converts radians to degree
print(B)

[ 45.  60.  90. 180.]


In [ ]:
np.deg2rad(B)

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(1)#radians

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

statistics

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st)#std=sqrt((sigma(xi-x)^2)/n) where xi=indvidual element and x = mean n= no of elements

24.452334585202017

In [ ]:
np.var(st)#var=(std)^2

597.9166666666666

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(C)#linear algebra is a sub pakage in numpy

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=np.arange(1,25).reshape(6,4)
print(C)
print(np.argmax(C))#argmax will provide you the index of highest number in the given matrix

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
23


In [ ]:
C=np.floor(10*np.random.rand(24)).reshape(6,4)
print(C)

[[1. 4. 0. 7.]
 [3. 6. 5. 8.]
 [9. 4. 0. 1.]
 [3. 0. 2. 9.]
 [1. 1. 8. 4.]
 [3. 1. 5. 3.]]


In [ ]:
print(np.argmax(C))#highest element in matrix is 9 and it is present in both 8th and 15th postion
#but argmax consider the 8th position element as it comes first while traversing

8


In [ ]:
D=10*np.random.rand(24).reshape(6,4)
print(D)

[[6.44404866 1.86020535 0.27262437 6.25177854]
 [9.59072609 6.66088224 4.59422427 2.19808141]
 [9.9885429  6.57685544 3.26439498 2.98370284]
 [5.46829114 9.3397044  9.49611905 4.95345547]
 [2.16455952 9.81523651 9.70353449 8.21954919]
 [2.44820214 3.38729735 5.78494259 0.36974223]]


In [ ]:
print(np.argmax(D,axis=1))#argmax with axis=1 will provide you the index of highest number in each individual row in the given matrix

[0 0 0 2 1 2]


In [ ]:
print(np.argmax(D,axis=0))#argmax with axis=0 will provide you the index of highest number in each individual coloumn in the given matrix

[2 4 4 4]


we can use argmin as like argmax

In [ ]:
print(np.argmin(D,axis=1))

[2 3 3 3 0 3]


In [ ]:
print(np.argmin(D,axis=0))

[4 0 0 5]


searching the indices based on conditions

In [ ]:
#finding indixes where the values are even
a=np.array([34,56,17,89,91])
print(np.where(a%2==0))

(array([0, 1]),)


In [ ]:
b=np.array([24,16,7,17,54,60])
print(np.where(b%6==0))

(array([0, 4, 5]),)


In [ ]:
#searching is done only for sorted list
a=np.array([6,7,8,9,10])
x=np.searchsorted(a,10)
print(x)

4


In [ ]:
#unsorted list
b=np.array([34,12,7])
x=np.searchsorted(b,7)
print(x)

0


sorting array

In [ ]:
arr=np.array(['banana','cherry','apple'])
ar=np.array([True, False, True])#VALUE FOR FALSE=0 AND VALUE FOR TRUE=1
print(np.sort(arr))
print(np.sort(ar))

['apple' 'banana' 'cherry']
[False  True  True]


In [ ]:
#2d-sort:sorting happens within a row
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


Filter

In [ ]:
#array filter
arr=np.array([40,42,50,44,67,78])
x=[True,False,True,False,True,True]#filter list
newarr=arr[x]
print(newarr)

[40 50 67 78]


In [ ]:
arr=np.array([40,43,50,44,67,78])
filt=np.where(arr%2==0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
arr[filt]#array_name[index]

array([40, 50, 44, 78])

itterating through 2 arrays

In [ ]:
names=np.array(["kusu","teju","rams","veens","sadhu","kavs","varsh","lorry"])
initials=np.array(["B","E","G","J","M","T","V","Y"])
for i,j in zip(initials,names):
  print(i,".",j)


B . kusu
E . teju
G . rams
J . veens
M . sadhu
T . kavs
V . varsh
Y . lorry


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n1=np.multiply(a1,a2)
print(n1)

[ 200  420  660  920 1200 1500]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n2=np.divide(a1,a2)
print(n2)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n3=np.mod(a1,a2)
print(n3)

[10 20  8 17  2 10]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n4=np.divmod(a1,a2)
print(n4)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


logarithms

In [ ]:
a1=1.2
print(np.log(a1))#natural log e

0.1823215567939546


In [ ]:
a1=1.2
print(np.log2(a1))#log base 2

0.2630344058337938


In [ ]:
a1=1.2
print(np.log10(a1))#log base 10

0.07918124604762482


In [ ]:
a=np.array([1,2,3,4,5,6,7])
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015]


In [ ]:
a=np.array([1,2,3,4,5,6,7])
print(np.log2(a))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492]


other mathematical functions

In [ ]:
#cummulative product
a1=np.array([5,6,7,10])
x=np.cumprod(a1)
print(x)

[   5   30  210 2100]


In [ ]:
#cummulative sum
a1=np.array([5,6,7,10])
x=np.cumsum(a1)
print(x)

[ 5 11 18 28]


In [ ]:
#differnce
a2=np.array([10,15,25,15])#e2-e1
new=np.diff(a2)
print(new)

[  5  10 -10]


In [ ]:
#lcm
n1=455
n2=665
x=np.lcm(n1,n2)
print(x)

8645


In [ ]:
#gcd
n1=455
n2=665
x=np.gcd(n1,n2)
print(x)

35


In [ ]:
#finding gcd for array of elements
a=np.array([12,15,60])
gc=np.gcd.reduce(a)#takes multiple inputs and gives single output
print(gc)

3


In [ ]:
#finding gcd for array of elements
a=np.array([12,15,60])
lc=np.lcm.reduce(a)#takes multiple inputs and gives single output
print(lc)

60
